DROP TABLE IF EXISTS bloco CASCADE;
CREATE TABLE bloco(
	id SERIAL PRIMARY KEY,
	codigo VARCHAR,
	descricao VARCHAR
)
INSERT INTO bloco (
    codigo,
    descricao
    ) VALUES
('dcod_est_cadastral_fam','Bloco 1 - Estado cadastral da família'),
('dfx_rfpc','Bloco 1 - Faixa da renda familiar per capita'),
('dcod_forma_coleta_fam','Bloco 1 - Forma de coleta'),
('dqtde_meses_desat_cat','Bloco 1 - Número de meses após a última atualização cadastral'),
('dmarc_pbf','Bloco 1 - Recebe PBF família'),
('dcod_calcamento_domic_fam','Bloco 2 - Calçamento em frente ao seu domicílio'),
('dcod_local_domic_fam','Bloco 2 - Situação do domicílio'),
('dcod_especie_domic_fam','Bloco 2 - Espécie do domicílio'),
('dcod_banheiro_domic_fam','Bloco 2 - Existência de banheiro'),
('dcod_abaste_agua_domic_fam','Bloco 2 - Forma de abastecimento de água'),
('dcod_destino_lixo_domic_fam','Bloco 2 - Forma de coleta do lixo'),
('dcod_escoa_sanitario_domic_fam','Bloco 2 - Forma de escoamento sanitário'),
('dcod_material_domic_fam','Bloco 2 - Material preodiminante nas paredes externas do domicílio'),
('dcod_material_piso_fam','Bloco 2 - Material preodiminante no piso do domicílio'),
('dcod_agua_canalizada_fam','Bloco 2 - Água canalizada no domicílio'),
('dcod_iluminacao_domic_fam','Bloco 2 - Tipo de iluminação'),
('dcod_familia_indigena_fam','Bloco 3 - Família Indígena'),
('dind_familia_quilombola_fam','Bloco 3 - Família quilombola'),
('pcod_raca_cor_pessoa','Bloco 4 - Cor ou raça'),
('pcod_est_cadastral_memb','Bloco 4 - Estado cadastral da pessoa'),
('pfx_idade','Bloco 4 - Faixa etária'),
('pmarc_pbf','Bloco 4 - Recebe PBF pessoa'),
('pcod_parentesco_rf_pessoa','Bloco 4 - Relação de parentesco com responsável familiar'),
('pcod_sexo_pessoa','Bloco 4 - Sexo'),
('pind_trabalho_infantil_pessoa','Bloco 4 - Pessoa com marcação de trabalho infantil'),
('pind_ajuda_especializado_memb','Bloco 6 - Recebe ajuda de cuidador especializado'),
('pind_ajuda_familia_memb','Bloco 6 - Recebe ajuda de alguém da família'),
('pind_ajuda_instituicao_memb','Bloco 6 - Recebe ajuda de instituição'),
('pind_ajuda_nao_memb','Bloco 6 - Não recebe ajuda de terceiros'),
('pind_ajuda_outra_memb','Bloco 6 - Recebe ajuda de outra forma'),
('pind_ajuda_vizinho_memb','Bloco 6 - Recebe ajuda de vizinho'),
('pind_def_cegueira_memb','Bloco 6 - Cegueira'),
('pind_def_sindrome_down_memb','Bloco 6 - Síndrome de Down'),
('pind_def_fisica_memb','Bloco 6 - Deficiência física'),
('pind_def_mental_memb','Bloco 6 - Deficiência mental ou intelectual'),
('pind_def_surdez_leve_memb','Bloco 6 - Surdez leve/moderada'),
('pind_def_surdez_profunda_memb','Bloco 6 - Surdez severa/profunda'),
('pind_def_transtorno_mental_memb','Bloco 6 - Transtorno/doença mental'),
('pind_def_baixa_visao_memb','Bloco 6 - Baixa visão'),
('pcod_deficiencia_memb','Bloco 6 - Pessoa tem deficiência'),
('pcod_ano_serie_frequenta_memb','Bloco 7 - Ano e série do curso que a pessoa frequenta'),
('pcod_concluiu_frequentou_memb','Bloco 7 - A pessoa concluiu o curso?'),
('pcod_curso_frequentou_pessoa_memb','Bloco 7 - Curso mais elevado que a pessoa frequentou'),
('pcod_curso_frequenta_memb','Bloco 7 - Curso que a pessoa frequenta'),
('pgrau_instrucao','Bloco 7 - Grau de instrução'),
('pind_frequenta_escola_memb','Bloco 7 - Pessoa frequenta escola'),
('pcod_sabe_ler_escrever_memb','Bloco 7 - Pessoa sabe ler e escrever'),
('pcod_ano_serie_frequentou_memb','Bloco 7 - Último ano e série do curso que a pessoa frequentou'),
('pcod_agricultura_trab_memb','Bloco 8 - Atividade extrativista'),
('pcod_principal_trab_memb','Bloco 8 - Função principal'),
('pcod_afastado_trab_memb','Bloco 8 - Pessoa estava afastada na semana passada? '),
('pcod_trabalho_12_meses_memb','Bloco 8 - Trabalho remunerado nos últimos 12 meses'),
('pcod_trabalhou_memb','Bloco 8 - Pessoa trabalhou na semana passada?'),
('dind_parc_mds_fam','Bloco 11 - Grupos Populacionais Tradicionais e Específicos'),
('pmarc_sit_rua','Bloco 12 - Situação de Rua')