CREATE TABLE listaDados(
	id SERIAL PRIMARY KEY,
	codigo VARCHAR,
	descricao VARCHAR,
	disponibilidade BOOLEAN,
	nome_tabela VARCHAR,
	valor VARCHAR
);

--INSERT DATAS
INSERT INTO listaDados (
codigo,
descricao,
disponibilidade,
nome_tabela,
valor
) VALUES
('dcd_ibge','Codigo do municipio',true,'',''),
('dcod_familiar_fam','Codigo familiar',true,'',''),
('ddat_cadastramento_fam','Data de cadastramento da familia',true,'',''),
('ddat_atual_fam','Data da ultima atualizacao da familia',true,'',''),
('dcod_est_cadastral_fam','Estado cadastral da familia',true,'estadocadastral',''),
('dcod_forma_coleta_fam','Forma de coleta',true,'',''),
('ddta_entrevista_fam','Data da entrevista',true,'',''),
('dnom_localidade_fam','Nome da localidade',true,'',''),
('dnom_tip_logradouro_fam','Tipo de logradouro',true,'',''),
('dnom_titulo_logradouro_fam','Titulo do logradouro',true,'',''),
('dnom_logradouro_fam','Nome do logradouro',true,'',''),
('dnum_logradouro_fam','Numero do logradouro',true,'',''),
('ddes_complemento_fam','Complemento do numero',true,'',''),
('ddes_complemento_adic_fam','Complemento adicional',true,'',''),
('dnum_cep_logradouro_fam','CEP',true,'',''),
('dcod_unidade_territorial_fam','Codigo da unidade territorial local',true,'',''),
('dnom_unidade_territorial_fam','Nome da unidade territorial local',true,'',''),
('dtxt_referencia_local_fam','Referencia para localizacao do endereco',true,'',''),
('dnom_entrevistador_fam','Nome do entrevistador',true,'',''),
('dnum_cpf_entrevistador_fam','CPF do entrevistador',true,'',''),
('dvlr_renda_media_fam','Valor da renda familiar per capita',true,'',''),
('dfx_rfpc','Faixa da renda familiar per capita',true,'',''),
('dvlr_renda_total_fam','Valor da renda total da familia',true,'',''),
('dmarc_pbf','Recebe PBF pessoa',true,'pbf',''),
('dqtde_meses_desat_cat','Numero de meses apos a ultima atualizacao cadastral',true,'',''),
('dcod_local_domic_fam','Situacao do domicilio',true,'',''),
('dcod_especie_domic_fam','Especie do domicilio',true,'',''),
('dqtd_comodos_domic_fam','Quantidade de comodos do domicilio',true,'',''),
('dqtd_comodos_dormitorio_fam','Comodo servindo como dormitorio do domicilio',true,'',''),
('dcod_material_piso_fam','Material predominante no piso do domicilio',true,'',''),
('dcod_material_domic_fam','Material predominante nas paredes externas do domicilio',true,'',''),
('dcod_agua_canalizada_fam','Água canalizada no domicilio',true,'',''),
('dcod_abaste_agua_domic_fam','Forma de abastecimento de agua',true,'',''),
('dcod_banheiro_domic_fam','Existencia de banheiro',true,'',''),
('dcod_escoa_sanitario_domic_fam','Forma de escoamento sanitario',true,'',''),
('dcod_destino_lixo_domic_fam','Forma de coleta do lixo',true,'',''),
('dcod_iluminacao_domic_fam','Tipo de iluminacao',true,'',''),
('dcod_calcamento_domic_fam','Calcamento em frente ao seu domicilio',true,'',''),
('dcod_familia_indigena_fam','Familia Indigena',true,'',''),
('dcod_povo_indigena_fam','Codigo de povo indigena',true,'',''),
('dnom_povo_indigena_fam','Nome do povo indigena',true,'',''),
('dcod_indigena_reside_fam','Reside em reserva indigena',true,'',''),
('dcod_reserva_indigena_fam','Codigo da reserva indigena',true,'',''),
('dnom_reserva_indigena_fam','Nome da reserva indigena',true,'',''),
('dind_familia_quilombola_fam','Familia quilombola',true,'',''),
('dcod_comunidade_quilombola_fam','Codigo da comunidade quilombola',true,'',''),
('dnom_comunidade_quilombola_fam','Nome da comunidade quilombola',true,'',''),
('dqtd_pessoas_domic_fam','Quantidade de pessoas no domicilio',true,'',''),
('dqtd_familias_domic_fam','Quantidade de familias no domicilio',true,'',''),
('dqtd_pessoa_inter_0_17_anos_fam','Quantidade de pessoas internadas faixa 0-17 anos',true,'',''),
('dqtd_pessoa_inter_18_64_anos_fam','Quantidade de pessoas internadas faixa 18-59 anos',true,'',''),
('dqtd_pessoa_inter_65_anos_fam','Quantidade de pessoas internadas faixa 60 anos ou mais',true,'',''),
('dval_desp_energia_fam','Valor de despesas com energia',true,'',''),
('dval_desp_agua_esgoto_fam','Valor de despesas com agua',true,'',''),
('dval_desp_gas_fam','Valor de despesas com gas',true,'',''),
('dval_desp_alimentacao_fam','Valor de despesas com alimentacao',true,'',''),
('dval_desp_transpor_fam','Valor de despesas com transporte',true,'',''),
('dval_desp_aluguel_fam','Valor de despesas com aluguel',true,'',''),
('dval_desp_medicamentos_fam','Valor de despesas com medicamentos',true,'',''),
('dnom_estab_assist_saude_fam','Nome do estabelecimento EAS/MS',true,'',''),
('dcod_eas_fam','Codigo do estabelecimento EAS/MS',true,'',''),
('dnom_centro_assist_fam','Nome do CRAS/CREAS',true,'',''),
('dcod_centro_assist_fam','Codigo do CRAS/CREAS',true,'',''),
('dnum_ddd_contato_1_fam','Estado cadastral da pessoa',true,'',''),
('dnum_tel_contato_1_fam','Numero do telefone primario',true,'',''),
('dic_tipo_contato_1_fam','Tipo do telefone primario',true,'',''),
('dic_envo_sms_contato_1_fam','Autoriza envio de mensagem para telefone primario',true,'',''),
('dnum_tel_contato_2_fam','Numero do telefone secundario',true,'',''),
('dnum_ddd_contato_2_fam','DDD do telefone secundario',true,'',''),
('dic_tipo_contato_2_fam','Tipo do telefone secundario',true,'',''),
('dic_envo_sms_contato_2_fam','Autoriza envio de mensagem para telefone secundario',true,'',''),
('dcod_cta_energ_unid_consum_fam','Codigo da unidade consumidora associado a conta de energia eletrica do domicilio',true,'',''),
('dind_parc_mds_fam','Grupos Populacionais Tradicionais e Especificos',true,'',''),
('dref_cad','Referencia Cadastro Unico',true,'',''),
('dref_pbf','Referencia Programa Bolsa Familia',true,'',''),
('pcod_familiar_fam','Codigo familiar',true,'',''),
('pcod_est_cadastral_memb','Estado cadastral da pessoa',true,'',''),
('pind_trabalho_infantil_pessoa','Pessoa com marcacao de trabalho infantil',true,'',''),
('pnom_pessoa','Nome',true,'',''),
('pnum_nis_pessoa_atual','NIS',true,'',''),
('pnom_apelido_pessoa','Apelido/Nome Social',true,'',''),
('pcod_sexo_pessoa','Sexo',true,'',''),
('pdta_nasc_pessoa','Data de nascimento',true,'',''),
('pcod_parentesco_rf_pessoa','Relacao de parentesco com o responsavel familiar',true,'',''),
('pcod_raca_cor_pessoa','Cor ou raca',true,'',''),
('pnom_completo_mae_pessoa','Nome da mae',true,'',''),
('pnom_completo_pai_pessoa','Nome do pai',true,'',''),
('pcod_local_nascimento_pessoa','Local de nascimento',true,'',''),
('psig_uf_munic_nasc_pessoa','UF de nascimento da pessoa',true,'',''),
('pnom_ibge_munic_nasc_pessoa','Nome do municipio de nascimento da pessoa',true,'',''),
('pcod_ibge_munic_nasc_pessoa','Codigo ibge do municipio de nascimento da pessoa',true,'',''),
('pnom_pais_origem_pessoa','Nome do pais de nascimento da pessoa',true,'',''),
('pcod_pais_origem_pessoa','Codigo do pais de nascimento da pessoa',true,'',''),
('pcod_certidao_registrada_pessoa','Nascimento registrado em Cartorio',true,'',''),
('pfx_idade','Faixa etaria',true,'',''),
('pmarc_pbf','Recebe PBF pessoa',true,'',''),
('pcod_certidao_civil_pessoa','Tipo de certidao',true,'',''),
('pcod_livro_termo_certid_pessoa','Numero do livro',true,'',''),
('pcod_folha_termo_certid_pessoa','Numero da folha',true,'',''),
('pcod_termo_matricula_certid_pessoa','Numero do termo',true,'',''),
('pnom_munic_certid_pessoa','Municipio do registro',true,'',''),
('pcod_ibge_munic_certid_pessoa','Codigo IBGE do municipio do registro',true,'',''),
('pcod_cartorio_certid_pessoa','Codigo do cartorio do registro',true,'',''),
('pnum_cpf_pessoa','CPF da pessoa',true,'',''),
('pnum_identidade_pessoa','Numero do RG',true,'',''),
('pcod_complemento_pessoa','Complemento do numero do RG',true,'',''),
('pdta_emissao_ident_pessoa','Data de emissao do RG',true,'',''),
('psig_uf_ident_pessoa','Estado emissor do RG',true,'',''),
('psig_orgao_emissor_pessoa','Sigla do orgao emissor do RG',true,'',''),
('pnum_cart_trab_prev_soc_pessoa','Numero da CTPS',true,'',''),
('pnum_serie_trab_prev_soc_pessoa','Serie da CTPS',true,'',''),
('pdta_emissao_cart_trab_pessoa','Data de emissao da CTPS',true,'',''),
('psig_uf_cart_trab_pessoa','Estado emissor da CTPS',true,'',''),
('pnum_titulo_eleitor_pessoa','Numero do Titulo de Eleitor',true,'',''),
('pnum_zona_tit_eleitor_pessoa','Zona do Titulo de Eleitor',true,'',''),
('pnum_secao_tit_eleitor_pessoa','Secao do Titulo de Eleitor',true,'',''),
('pcod_deficiencia_memb','Pessoa tem deficiencia',true,'',''),
('pind_def_cegueira_memb','Cegueira',true,'',''),
('pind_def_baixa_visao_memb','Baixa visao',true,'',''),
('pind_def_surdez_profunda_memb','Surdez severa/profunda',true,'',''),
('pind_def_surdez_leve_memb','Surdez leve/moderada',true,'',''),
('pind_def_fisica_memb','Deficiencia fisica',true,'',''),
('pind_def_mental_memb','Deficiencia mental ou intelectual',true,'',''),
('pind_def_sindrome_down_memb','Sindrome de Down',true,'',''),
('pind_def_transtorno_mental_memb','Transtorno/doenca mental',true,'',''),
('pind_ajuda_nao_memb','Nao recebe ajuda de terceiros',true,'',''),
('pind_ajuda_familia_memb','Recebe ajuda de alguem da familia',true,'',''),
('pind_ajuda_especializado_memb','Recebe ajuda de cuidador especializado',true,'',''),
('pind_ajuda_vizinho_memb','Recebe ajuda de vizinho',true,'',''),
('pind_ajuda_instituicao_memb','Recebe ajuda de instituicao',true,'',''),
('pind_ajuda_outra_memb','Recebe ajuda de outra forma',true,'',''),
('pcod_sabe_ler_escrever_memb','Pessoa sabe ler e escrever',true,'',''),
('pind_frequenta_escola_memb','Pessoa frequenta escola',true,'',''),
('pnom_escola_memb','Nome da escola da pessoa',true,'',''),
('pcod_escola_local_memb','Escola localizada no municipio',true,'',''),
('psig_uf_escola_memb','UF da escola da pessoa',true,'',''),
('pnom_munic_escola_memb','Nome do municipio da escola da pessoa',true,'',''),
('pcod_ibge_munic_escola_memb','Codigo do ibge do municipio da escola da pessoa',true,'',''),
('pcod_censo_inep_memb','Codigo INEP da escola da pessoa',true,'',''),
('pcod_curso_frequenta_memb','Curso que a pessoa frequenta',true,'',''),
('pcod_ano_serie_frequenta_memb','Ano e serie do curso que a pessoa frequenta',true,'',''),
('pcod_curso_frequentou_pessoa_memb','Curso mais elevado que a pessoa frequentou',true,'',''),
('pcod_ano_serie_frequentou_memb','Ultimo ano e serie do curso que a pessoa frequentou',true,'',''),
('pcod_concluiu_frequentou_memb','A pessoa concluiu o curso',true,'',''),
('pgrau_instrucao','Grau de instrucao',true,'',''),
('pcod_trabalhou_memb','Pessoa trabalhou na semana passada',true,'',''),
('pcod_afastado_trab_memb','Pessoa estava afastada na semana passada',true,'',''),
('pcod_agricultura_trab_memb','Atividade extrativista',true,'',''),
('pcod_principal_trab_memb','Funcao principal',true,'',''),
('pval_remuner_emprego_memb','Valor de remuneracao do mes passado do trabalho principal',true,'',''),
('pcod_trabalho_12_meses_memb','Trabalho remunerado nos ultimos 12 meses',true,'',''),
('pqtd_meses_12_meses_memb','Quantidade de meses trabalhados nos ultimos 12 meses',true,'',''),
('pval_renda_bruta_12_meses_memb','Remuneracao bruta de todos os trabalhos nos ultimos 12 meses',true,'',''),
('pval_renda_doacao_memb','Valor recebido de doacao',true,'',''),
('pval_renda_aposent_memb','Valor recebido de aposentadoria',true,'',''),
('pval_renda_seguro_desemp_memb','Valor recebido de seguro desemprego',true,'',''),
('pval_renda_pensao_alimen_memb','Valor recebido de pensao alimenticia',true,'',''),
('pval_outras_rendas_memb','Valor recebido de outras fontes',true,'',''),
('pmarc_sit_rua','Situacao de Rua',true,'',''),
('pind_dormir_rua_memb','Dorme na rua',true,'',''),
('pqtd_dormir_freq_rua_memb','Quantidade de vezes por semana que dorme na rua',true,'',''),
('pind_dormir_albergue_memb','Dorme em albergue',true,'',''),
('pqtd_dormir_freq_albergue_memb','Quantidade de vezes por semana que dorme em albergue',true,'',''),
('pind_dormir_dom_part_memb','Dorme em domicilio particular',true,'',''),
('pqtd_dormir_freq_dom_part_memb','Quantidade de vezes por semana que dorme em domicilio particular',true,'',''),
('pind_outro_memb','Dorme de outra forma',true,'',''),
('pqtd_freq_outro_memb','Quantidade de vezes por semana que dorme de outra forma',true,'',''),
('pcod_tempo_rua_memb','Tempo em que vive na rua',true,'',''),
('pind_motivo_perda_memb','Motivo da condicao de rua por perda de moradia',true,'',''),
('pind_motivo_ameaca_memb','Motivo da condicao de rua por ameaca',true,'',''),
('pind_motivo_probs_fam_memb','Motivo da condicao de rua por problemas familiares',true,'',''),
('pind_motivo_alcool_memb','Motivo da condicao de rua por alcoolismo',true,'',''),
('pind_motivo_desemprego_memb','Motivo da condicao de rua por desemprego',true,'',''),
('pind_motivo_trabalho_memb','Motivo da condicao de rua por trabalho',true,'',''),
('pind_motivo_saude_memb','Motivo da condicao de rua por tratamento de saude',true,'',''),
('pind_motivo_pref_memb','Motivo da condicao de rua por preferencia',true,'',''),
('pind_motivo_outro_memb','Motivo da condicao de rua por outro motivo',true,'',''),
('pind_motivo_nao_sabe_memb','Nao sabe/nao lembra o motivo da condicao de rua',true,'',''),
('pind_motivo_nao_resp_memb','Nao respondeu o motivo da condicao de rua',true,'',''),
('pcod_tempo_cidade_memb','Tempo em que mora na cidade',true,'',''),
('pcod_vive_fam_rua_memb','Vive com sua familia na rua',true,'',''),
('pcod_contato_parente_memb','Tem contato com parente fora da condicao de rua',true,'',''),
('pind_ativ_com_escola_memb','Atividade comunitaria em escola',true,'',''),
('pind_ativ_com_coop_memb','Atividade comunitaria em cooperativa',true,'',''),
('pind_ativ_com_mov_soc_memb','Atividade comunitaria em movimento social',true,'',''),
('pind_ativ_com_nao_sabe_memb','Nao sabe se frequentou atividade comunitaria',true,'',''),
('pind_ativ_com_nao_resp_memb','Nao respondeu se frequentou atividade comunitaria',true,'',''),
('pind_atend_cras_memb','Atendido por cras',true,'',''),
('pind_atend_creas_memb','Atendido por creas',true,'',''),
('pind_atend_centro_ref_rua_memb','Atendido por centro ref pop rua',true,'',''),
('pind_atend_inst_gov_memb','Atendido por instituicao governamental',true,'',''),
('pind_atend_inst_nao_gov_memb','Atendido por instituicao nao-governamental',true,'',''),
('pind_atend_hospital_geral_memb','Atendido por hospital/clinica geral',true,'',''),
('pcod_cart_assinada_memb','Teve emprego com carteira assinada',true,'',''),
('pind_dinh_const_memb','Ganha dinheiro com construcao civil',true,'',''),
('pind_dinh_flanelhinha_memb','Ganha dinheiro como guardador de carro',true,'',''),
('pind_dinh_carregador_memb','Ganha dinheiro como carregador',true,'',''),
('pind_dinh_catador_memb','Ganha dinheiro como catador',true,'',''),
('pind_dinh_servs_gerais_memb','Ganha dinheiro com servicos gerais',true,'',''),
('pind_dinh_pede_memb','Ganha dinheiro como pedinte',true,'',''),
('pind_dinh_vendas_memb','Ganha dinheiro com vendas',true,'',''),
('pind_dinh_outro_memb','Ganha dinheiro de outra forma',true,'',''),
('pind_dinh_nao_resp_memb','Nao respondeu como ganha dinheiro',true,'',''),
('pind_atend_nenhum_memb','Nao foi atendido por nenhum local',true,'',''),
('pref_cad','Referencia Cadastro Unico',true,'',''),
('pref_pbf','Referencia Programa Bolsa Familia',true,'','');